DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS verificationToken;
DROP TABLE IF EXISTS pools;
DROP TABLE IF EXISTS pool_members;
DROP TABLE IF EXISTS canvases;
DROP TABLE IF EXISTS files; 