DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS verificationTokens;
DROP TABLE IF EXISTS pools;
DROP TABLE IF EXISTS pool_members;
DROP TABLE IF EXISTS canvases;
DROP TABLE IF EXISTS files; 